### ISSUE TITLE
Plugin activation attempt triggered fatal error

### ISSUE THREAD

**Issue by finleykjames** [post-duif/integration-listmonk-wordpress-plugin#28]
I installed the plugin and tried activating it. My WP said that the plugin could not be activated because it triggered a fatal error. Everything is fully updated, so I'm not sure if it's an issue in the plugin itself or if I'm doing something wrong.

**Comment by post-duif** [comment]
Thanks for letting me know! Could you please provide the error logs so I can troubleshoot this? Do you have the most recent WordPress installed? Do you you have WooCommerce installed?

**Comment by finleykjames** [comment]
It was an error on my end; I hadn't fully updated WP. Sorry!

**Comment by post-duif** [comment]
> It was an error on my end; I hadn't fully updated WP. Sorry! 

No worries! Did you get the plugin working with listmonk for your use case? I haven't received much feedback yet so I'd be happy to hear.
