### ISSUE TITLE
Possibility to add class(es) and localization to checkbox in WooCommerce checkout 

### ISSUE THREAD

**Issue by CodeShakingSheep** [post-duif/integration-listmonk-wordpress-plugin#31]
Hi,
First of all, thanks a lot for this plugin. I appreciate it :)
I just have some minor suggestions:

- Define class(es) for checkbox: In my builder all the checkboxes have a certain class which determines the styling. Of course, I could just manually apply the same CSS to the checkbox but I think it would be cleaner to have the possibility to add a class.
- Add localization: I'm not sure if this is in the scope of this plugin, but I run my website in 2 different languages (with Falang) and I didn't find a quick solution to change the opt-in text for my second language. Any suggestions for this?

Thanks and best

**Comment by CodeShakingSheep** [comment]
Hi @post-duif ,
Thanks for your reply. Yes, I checked out the integration on WooCommerce checkout on my staging site. The id on the newsletter checkbox is "newsletter_optin". Yes, it works. I just think assigning a class would be more efficient :smirk: Regarding localization with Falang I already figured it out (I could just go to "Translate Options" and then search for "Listmonk". There I could translate the subscription string. So, I think I'm all set for now. Thanks for the plugin :pray:

**Comment by post-duif** [comment]
> Hi @post-duif , Thanks for your reply. Yes, I checked out the integration on WooCommerce checkout on my staging site. The id on the newsletter checkbox is "newsletter_optin". Yes, it works. I just think assigning a class would be more efficient 😏 Regarding localization with Falang I already figured it out (I could just go to "Translate Options" and then search for "Listmonk". There I could translate the subscription string. So, I think I'm all set for now. Thanks for the plugin 🙏

Please note the label value changed in v1.3.7: https://github.com/post-duif/integration-listmonk-wordpress-plugin/releases/tag/v1.3.7. It changed to listmonk_newsletter_optin. Hope this doesn't cause you too much trouble.

**Comment by post-duif** [comment]
@CodeShakingSheep please not that I am developing this plugin in my free time! Feel free to donate if you want to support development: https://www.buymeacoffee.com/postduif.

As for the class, are you sure CF7 adds CSS classes to checkboxes in the WooCommerce checkout? There are classes already assigned to checkboxes by WooCommerce by default, and I do not think you can change them. I did add an id (listmonk_newsletter_optin) to the checkbox in WooCommerce checkout.

Please refer to the html of a WooCommerce checkout form, where you can see it adopts the "input-checkbox" class, which you can use for custom CSS.

Perhaps a screenshot of the interface you use / WooCommerce checkout as you would like to see it, would help.

**Comment by CodeShakingSheep** [comment]
> @CodeShakingSheep please note that I am developing this plugin in my free time! Feel free to donate if you want to support development: https://www.buymeacoffee.com/postduif.
> 
> As for the class, are you sure CF7 adds CSS classes to checkboxes in the WooCommerce checkout? There are classes already assigned to checkboxes by WooCommerce by default, and I do not think you can change them. I did add an id (listmonk_newsletter_optin) to the checkbox in WooCommerce checkout.
> 
> Please refer to the html of a WooCommerce checkout form, where you can see it adopts the "input-checkbox" class, which you can use for custom CSS.
> 
> Perhaps a screenshot of the interface you use / WooCommerce checkout as you would like to see it, would help.

I didn't mean to offend you. I'm contributing quite a bit to open source as well in my free time. So, I can see where you're coming from. As I wrote in my initial post, I appreciate this plugin! So as for the CSS styling it's fine for now. I can use the id for styling or the class "input-checkbox". Don't worry about my initial request. It was just a minor issue. 

Regarding your question for my use case. I'm using the plugin for the checkbox in the WooCommerce checkout. And thank you again for your work with this plugin!

**Comment by post-duif** [comment]
> > @CodeShakingSheep please note that I am developing this plugin in my free time! Feel free to donate if you want to support development: https://www.buymeacoffee.com/postduif.
> > 
> > As for the class, are you sure CF7 adds CSS classes to checkboxes in the WooCommerce checkout? There are classes already assigned to checkboxes by WooCommerce by default, and I do not think you can change them. I did add an id (listmonk_newsletter_optin) to the checkbox in WooCommerce checkout.
> > 
> > Please refer to the html of a WooCommerce checkout form, where you can see it adopts the "input-checkbox" class, which you can use for custom CSS.
> > 
> > Perhaps a screenshot of the interface you use / WooCommerce checkout as you would like to see it, would help.
> 
> I didn't mean to offend you. I'm contributing quite a bit to open source as well in my free time. So, I can see where you're coming from. As I wrote in my initial post, I appreciate this plugin! So as for the CSS styling it's fine for now. I can use the id for styling or the class "input-checkbox". Don't worry about my initial request. It was just a minor issue. 
> 
> Regarding your question for my use case. I'm using the plugin for the checkbox in the WooCommerce checkout. And thank you again for your work with this plugin!

Thanks for your kind words! Not offended at all, and thanks for the feedback again :)
