### ISSUE TITLE
Feature Request: send a blog post as a campaign

### ISSUE THREAD

**Issue by msklywenn** [post-duif/integration-listmonk-wordpress-plugin#38]
Hello,
I'd want to be able to turn any wordpress post into a campaign on listmonk. Ideally, it would also add a link to the original post and the usual unsubscribe button.
Is that planned? Is there any other plugin achieving this functionality?
Thanks in advance,

**Comment by post-duif** [comment]
Thanks for your interest in the plugin, that's something far out of scope. You could try building something like that yourself with the listmonk API.

-------- Original Message --------
